
pairs = [[r"my name is (.*)", 
            ["Hello %1, How are you today ?",]],
        [r"what (.*) your name ?", 
            ["My name is Jarvis and I'm a chatbot ?",]],
        [r"how are you ?|you are fine ?", 
            ["I'm doing good\nHow about You ?",]],
        [r"(.*)fine", 
            ["your welcome","I'm happy for you",]],
        [r"sorry (.*)", 
            ["Its alright","Its OK, never mind",]],
        [r"i'm (.*) doing good", 
            ["Nice to hear that","Alright :)",]],
        [r"hi|hey|hello", 
            ["Hello", "Hey there :smiley: ",
            "Hello... I'm glad you could drop by today.",
            "Hi there... how are you today?",
            "Hello, how are you feeling today?",]],
        [r"(.*) age ?|how old (.*)", 
            ["I'm a computer program dude\nSeriously you are asking me this?",]],
        [r"what (.*) want ?", 
            ["Make me an offer\n I can't refuse",]],
        [r"(.*) why?",
            ["It's life Dude!"]],
        [r"(.*) created ?", 
            ["StarckTeam created me using Python's NLTK library ","top secret ;)",]],
        [r"where do you (come from|live) ?", 
            ['I live in a computer, and you ?',]],
        [r"(.*) (location|city) ?", 
            ['I live in a computer, and you ?',]],
        [r"how is weather in (.*)?",
            ["Weather in %1 is awesome like always","Too hot man here in %1",
            "Too cold man here in %1","Never even heard about %1"]],
        [r"i work in (.*)?", 
            ["%1 is an Amazing company, I have heard about it. But they are in huge loss these days.",]],
        [r"(.*)raining in (.*)", 
            ["No rain since last week here in %2","Damn its raining too much here in %2"]], 
        [r"how (.*) health(.*)",
            ["I'm a computer program, so I'm always healthy ",]], 
        [r"(.*) (sports|game) ?", 
            ["I'm a very big fan of Football",]], 
        [r"who (.*) sports person ?", 
            ["Messy","Ronaldo","Roony"]],
        [r"who (.*) (moviestar|actor) ?", ["Brad Pitt"]],
        [r"quit|bye",
            ["BBye take care. See you soon :) ", 
            "It was nice talking to you. See you soon :)"]],
        [r"Why don\'t you (.*)",
            ["Do you really think I don't %1?",
            "Perhaps eventually I will %1.",
            "Do you really want me to %1?",]],
        [r"Why can\'t I (.*)",
            ["Do you think you should be able to %1?",
            "If you could %1, what would you do?",
            "I don't know -- why can't you %1?",
            "Have you really tried?",]],
        [r"I am (.*)",
            ["Did you come to me because you are %1?",
            "How long have you been %1?",
            "How do you feel about being %1?",]],
        [r"I\'m (.*)",
            ["How does being %1 make you feel?",
            "Do you enjoy being %1?",
            "Why do you tell me you're %1?",
            "Why do you think you're %1?",]],
        [r"Are you (.*)",
            ["Why does it matter whether I am %1?",
            "Would you prefer it if I were not %1?",
            "Perhaps you believe I am %1.",
            "I may be %1 -- what do you think?",]],
        [r"Because (.*)",
            ["Is that the real reason?",
            "What other reasons come to mind?",
            "Does that reason apply to anything else?",
            "If %1, what else must be true?",]],
        [r"(.*) sorry (.*)",
            ["There are many times when no apology is needed.",
            "What feelings do you have when you apologize?",]],
        [r"I think (.*)",
            ["Do you doubt %1?", 
            "Do you really think so?", 
            "But you're not sure %1?"]],
        [r"(.*) friend (.*)",
            ["Tell me more about your friends.",
            "When you think of a friend, what comes to mind?",
            "Why don't you tell me about a childhood friend?",]],
        [r"Yes", ["You seem quite sure.", 
            "OK, but can you elaborate a bit?"]],
        [r"Can you (.*)",
            ["What makes you think I can't %1?",
            "If I could %1, then what?",
            "Why do you ask if I can %1?",]],
        [r"You are (.*)",
            ["Why do you think I am %1?",
            "Does it please you to think that I'm %1?",
            "Perhaps you would like me to be %1.",
            "Perhaps you're really talking about yourself?",]],
        [r"You\'re (.*)",
            ["Why do you say I am %1?",
            "Why do you think I am %1?",
            "Are we talking about you, or me?",]],
        [r"I feel (.*)",
            ["Good, tell me more about these feelings.",
            "Do you often feel %1?",
            "When do you usually feel %1?",
            "When you feel %1, what do you do?",]],
        [r"(.*) mother(.*)",
            ["Tell me more about your mother.",
            "What was your relationship with your mother like?",
            "How do you feel about your mother?",
            "How does this relate to your feelings today?",
            "Good family relations are important.",]],
         
]

